name: Invoke a test on push to development branch

on:
  push:
    branches:
      - development

jobs:
  call-endpoint-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call API using HTTP client action
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.usetrace.com/api/trace/ZoMfAR6weAAXXcb3jfGGG9QPEvnsqBMZ/execute'
          method: 'POST'
          contentType: 'application/json'
          data: '{
            "requiredCapabilities": [
              {
                "browserName": "chrome"
              }
            ],
            "reporters": [
              {
                "webhook": {
                  "url": "https://usetrace.free.beeceptor.com",
                  "when": "always"
                }
              }
            ]
          }'
