name: Invoke a test on push to development branch

on:
  push:
    branches:
      - development

jobs:
  test-usetrace-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Usetrace Webhook and Status Action
      uses: tarmac/usetrace-github-action@v1.0.0
      with:
        usetrace-api-key: ${{ secrets.USETRACE_API_KEY }}
        trace-id: ${{ vars.USETRACE_TRACE_ID }}
        webhook-url: ${{ vars.USETRACE_WEBHOOK_URL }}

    - name: Check Webhook Response
      run: |
        echo "Webhook triggered and status polled. Check the action logs for details."
