name: Invoke a Trace on Usetrace on push to development branch

on:
  push:
    branches:
      - development

jobs:
  test-usetrace-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Usetrace Trace and Wait for it to finish
      id: executeTrace
      uses: tarmac/usetrace-github-action@v1
      with:
        trace-id: ${{ vars.USETRACE_TRACE_ID }}

    - name: Check Trace execution result
      env:
        TRACE_RESULT: ${{ steps.executeTrace.outputs }}
      run: |
        echo "Trace result: $TRACE_RESULT"
