name: Invoke a Trace on Usetrace on push to development branch

on:
  push:
    branches:
      - development

jobs:
  test-usetrace-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Usetrace Trace and Wait for it to finish
      id: executeTrace
      uses: tarmac/usetrace-github-action@v1
      with:
        # Required parameters
        trigger-type: ${{ vars.USETRACE_TRIGGER_TYPE }} # Options: 'trace' or 'project')"
        trigger-id: ${{ vars.USETRACE_TRIGGER_ID }} # Id of the build to trigger.
        # trigger-id: ZoMdcx6weAAXXca7VhlygnfF8lGO5Pmo # Id of a test Project
        
        # Optional parameters
        browsers: chrome, firefox 127  # Coma separated list of browsers (ex: 'chrome, firefox'). You can specify a version of the browser this way: 'chrome 126, internet explorer 11' (version must be specified for internet explorer)
        base-url: https://de.wikipedia.org/ # baseUrl to execute against (defaults to the project baseUrl)"

        # Project Only Optional (only if trigger-type: project)
        tags: someothertag, smoke, flaky # Coma separated list of tags. Only traces with those tags would be run (by default runs all traces)"
        build-timeout-seconds: 120
        
    - name: Check Trace execution result
      env:
        BUILD_ID: ${{ steps.executeTrace.outputs.id }}
        STATUS: ${{ steps.executeTrace.outputs.status }}
        RESULT_REQUEST: ${{ steps.executeTrace.outputs.request }}
        RESULT_FINISH: ${{ steps.executeTrace.outputs.finish }}
        RESULT_PASS: ${{ steps.executeTrace.outputs.pass }}
        RESULT_FAIL: ${{ steps.executeTrace.outputs.fail }}
        RESULT_REPORT: ${{ steps.executeTrace.outputs.report }}
      run: |
        echo "Trace result: $BUILD_ID $STATUS $RESULT_REQUEST $RESULT_FINISH $RESULT_PASS $RESULT_FAIL "
        echo "REPORT: $RESULT_REPORT "
