name: Invoke a Trace on Usetrace on push to development branch
on:
  push:
    branches:
      - development

jobs:
  test-usetrace-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Usetrace Trace and Wait for it to finish
      id: executeTrace
      uses: usetrace/github-action@v1
      with:
        # Required parameters
        trigger-type: trace # Options: 'trace' or 'project')"
        trigger-id: ZpZ0IAQK1QAXhucMJKALXkvOEubUFFHj # Id of a test Project
        
    - name: Check Trace execution result
      env:
        RESULT_REPORT: $
      run: |
        echo "REPORT: $RESULT_REPORT"
