name: Invoke a Trace on Usetrace on push to development branch

on:
  push:
    branches:
      - development

jobs:
  test-usetrace-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Usetrace Trace and Wait for it to finish
      id: executeTrace
      uses: tarmac/usetrace-github-action@v1
      with:
        trigger-type: ${{ vars.USETRACE_TRIGGER_TYPE }} # Options: 'trace', 'project' or 'tag')"
        trigger-id: ${{ vars.USETRACE_TRIGGER_ID }} # Id of the build to trigger.

        test: |
          - something
          - somethingElse
            parameter: nothing

    - name: Check Trace execution result
      env:
        BUILD_ID: ${{ steps.executeTrace.outputs.id }}
        STATUS: ${{ steps.executeTrace.outputs.status }}
        RESULT_REQUEST: ${{ steps.executeTrace.outputs.request }}
        RESULT_FINISH: ${{ steps.executeTrace.outputs.finish }}
        RESULT_PASS: ${{ steps.executeTrace.outputs.pass }}
        RESULT_FAIL: ${{ steps.executeTrace.outputs.fail }}
        RESULT_REPORT: ${{ steps.executeTrace.outputs.report }}
      run: |
        echo "Trace result: $BUILD_ID $STATUS $RESULT_REQUEST $RESULT_FINISH $RESULT_PASS $RESULT_FAIL "
        echo "REPORT: $RESULT_REPORT "
